# This is a basic workflow to help you get started with Actions-Testing labels
name: learn-gha-tutorial

# With user defined run-name omitted
run-name: Run by @${{ github.actor }}

# Controls when the workflow will run
#Triggers the workflow on label creation troubleshoot
on:
  label:
    types: [created, deleted]
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
     - main
  pull_request:
    branches:
     - main 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Let us trigger the workflows with a concurrency group
  #group: ${{ github.head_ref || github.run_id }}
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true
  #with the context
  #github.ref determine the current branch name
  #group: ${{ github.ref }}
  #group: learn-concurrency
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print:
   runs-on: ubuntu-latest
   steps:
    - name: Run a one-line script
      run: |
          echo Hello to multi job understanding!
          sleep 30s
    
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, concurrency!
          sleep 2m
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Runs a github context
      - name: Runs a github context
        env:
              JOB_CONTEXT: ${{ toJson(github) }},
        run: echo "$JOB_CONTEXT"
